### ISSUE TITLE
Unknown group in CollateralReinvestmentGrp component

### ISSUE THREAD

**Issue by OptimumOpium** [FIXTradingCommunity/orchestrations#10]
Hi,

I have found that the **CollateralReinvestmentGrp** component contains a reference to the group with id **2266** which is not present in the dictionary at all.

```xml
<fixr:component name="CollateralReinvestmentGrp" id="2266" category="Common" added="FIX.5.0SP2" addedEP="254" abbrName="CollRnvstmnt">
	<fixr:groupRef added="FIX.5.0SP2" addedEP="254" id="2266">
		<fixr:annotation>
			<fixr:documentation/>
		</fixr:annotation>
	</fixr:groupRef>
	<fixr:annotation>
		<fixr:documentation purpose="SYNOPSIS">
 The CollateralReinvestmentGrp component block is a repeating group that may be used to provide a breakdown of the cash collateral's reinvestment types and amounts (e.g. CollateralType(1704)="CASH").
		</fixr:documentation>
		<fixr:documentation purpose="ELABORATION"/>
	</fixr:annotation>
</fixr:component>
```

Probably, that group had been missed when the dictionary was created. Or it's a mistake in the group id. Could you check it, please?

**Comment by donmendelson** [comment]
It looks like CollateralReinvestmentGrp should be a `<group>` rather than a `<component>`.  Investigating.

**Comment by rshriver** [comment]
This is a specification coding bug.  The group is coded as an XMLDataBlock and should be BlockRepeating.  SPEC-2441 ticket added.

**Comment by donmendelson** [comment]
The issue has already been registered for FIX Specification as "CollateralReinvestmentGrp component incorrectly coded as XMLDataBlock - should be BlockRepeating".

**Comment by kleihan** [comment]
Corrected with EP257
