### ISSUE TITLE
FIX 4.4 group has missing identifiers

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/orchestrations#13]
A repeating group in Logon message (35='A') is missing its identifiers. It appears to be MsgTypeGrp.

**Comment by kleihan** [comment]
FIX 4.4 base version ends with tag 956. The ID fields in MsgTypeGrp have higher tag numbers and were added with FIX 5.0, i.e. with EPs following the base version of FIX 4.4.

Could this be just FIXT 1.1 where the Logon message has a problem? I remember that we did not change session layer messages in FIXT anymore to avoid the need to increase the FIXT version number. FIXT 1.1 seems to have an empty MsgTypeGrp which is incorrect. Maybe this is a separate issue affecting the same repeating group.
