### ISSUE TITLE
NoStreamAssetAttributes(41237) = 'D' (Day)

### ISSUE THREAD

**Issue by jvirtanen** [FIXTradingCommunity/orchestrations#14]
In `OrchestraFIXLatest.xml`, the field NoStreamAssetAttributes(41237) has the type NumInGroup but also contains the code 'D' (Day). How should one handle this type discrepancy?

**Comment by kleihan** [comment]
This is an error that needs to be fixed, thank you for raising it.

![image](https://user-images.githubusercontent.com/13316841/98375388-515e5880-2042-11eb-9da5-8ceab2bbb6d1.png)

We will investigate and fix (no pun intended!) with the next update of FIX Latest.

**Comment by jvirtanen** [comment]
Great! Thank you for the quick response.

**Comment by donmendelson** [comment]
I believe that this was fixed in EP 259, soon to be published.
