### ISSUE TITLE
QuoteCondition(276) = "f " (FastMarketETH)

### ISSUE THREAD

**Issue by jvirtanen** [FIXTradingCommunity/orchestrations#16]
In `OrchestraFIXLatest.xml`, the QuoteCondition(276) value "f " (FastMarketETH) contains a trailing space character. All the other values consist of a single character. Is this an error or intentional?

This appears from FIX 5.0 onwards, and FIX protocol implementations have different approaches to handling it. [QuickFIX](https://github.com/quickfix/quickfix/blob/b6760f55ac6a46306b4e081bb13b65e6220ab02d/spec/FIX50.xml#L5483) retains the space character, while [QuickFIX/J](https://github.com/quickfix-j/quickfixj/blob/aab7d2c34e77c87016e76a6317c10aae5724baeb/quickfixj-messages/quickfixj-messages-fix50/src/main/resources/FIX50.xml#L5522) and [Philadelphia](https://github.com/paritytrading/philadelphia/blob/8f381840d079f1a1585b546d27a75096523f8819/libraries/fix50/src/main/java/com/paritytrading/philadelphia/fix50/FIX50Enumerations.java#L1196) (which I'm involved in) do not.

**Comment by kleihan** [comment]
Thanks for identifying this issue. It is clearly an error and needs to be fixed. We may add code to our validation software to ensure that values do not have any spaces in them, including leading or trailing spaces.
